### PR TITLE
Upgrade rails to 7

### PR DESCRIPTION
**Pull request by davidgisbey**
## What 

This PR upgrades Collections Publisher to use Rails 7.2

## Why 

Rails 7 was released in December 2021 and as we aim to keep up-to-date with Rails versions ([as per our Dependabot config](https://github.com/alphagov/content-publisher/blob/538b42a50263fc9c8c1054a4a60aaa4000e6b8d8/.github/dependabot.yml#L29-L30)) we should upgrade.

## Trello card 

https://trello.com/c/YBLhtdNm/400-upgrade-collections-publisher-from-rails-61x-to-70x

⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-own-pull-request) ⚠️

### CODE REVIEW

**Review by beccapearce — APPROVED** [review]
Looks good! Make sure to test it on integration first 😄

**Comment by davidgisbey** [comment]
Good shout. Have tested and added a commit for a fix!

**Comment by beccapearce** [comment]
Great! Let me know if you want me to merge it :)

**Comment by davidgisbey** [comment]
Yes please! @beccapearce

**Pull request merged**
