### PR TITLE
Prevent long titles in step nav wrapping buttons

### PR DESCRIPTION
**Pull request by selfthinker**
Before: 
screen shot 2018-03-27 at 12 07 19

After: 
screen shot 2018-03-27 at 12 07 39

[Trello card](https://trello.com/c/pAa4JrrZ)

### CODE REVIEW

**Comment by Davidslv** [comment]
Maybe a rebase will help get rid of that failure and we can merge it after.

**Comment by selfthinker** [comment]
Shouldn't it be fine to just run it again? (I cannot do that right now as I'm working from home.)

**Comment by selfthinker** [comment]
The main reason for a narrower table is because there are not many columns. Bootstrap always stretches the table to full width and when there are titles that are not that long, it can cause issues with screen magnifier users because they could miss that there is anything on the right-hand side.
It generally makes sense to keep an action as close to their "label" as possible. I guess it depends on how often we'll have long vs short titles. But so far it looks like short titles rule.

**Comment by sihugh** [comment]
👍

**Pull request merged**
