### PR TITLE
Remove optional / essential radio buttons

### PR DESCRIPTION
**Pull request by JonathanHallam**
Trello - https://trello.com/c/P1mSis5e/97-hide-optional-vs-essential-question-when-editing-step

Content designers say it wasn't being used consistently and it was confusing users

Pr to remove from Content Schemas
https://github.com/alphagov/govuk-content-schemas/pull/927

### CODE REVIEW

**Comment by JonathanHallam** [comment]
@AgaDufrat Good spot, hadn't realised this was a thing! Thanks :)

**Comment by brucebolt** [comment]
Do we need to do anything in the frontend app (`collections`) to deal with this change?

**Comment by JonathanHallam** [comment]
@brucebolt I've removed that line from `step_nav_presenter.rb`. I couldn't find any mention of `optional` or indeed SBS's in content store, what am I missing? Thanks!

**Comment by brucebolt** [comment]
It will be in `govuk-content-schemas`.  I _think_ it's these lines, but that'll need checking: https://github.com/alphagov/govuk-content-schemas/blob/master/dist/formats/step_by_step_nav/publisher_v2/schema.json#L242-L243

**Comment by JonathanHallam** [comment]
@brucebolt Nice one, thanks :) Have raised a PR to remove it there too
https://github.com/alphagov/govuk-content-schemas/pull/927

**Comment by JonathanHallam** [comment]
@brucebolt Done!

**Pull request merged**
