### PR TITLE
Send `content_id` to panopticon

### PR DESCRIPTION
**Pull request by tijmenb**
We need the `content_id` in panopticon for the new tagging infrastructure.

To make this change nice I've refactored the tests a little bit. More info in individual commits.

Trello: https://trello.com/c/IgYwT6yM

### CODE REVIEW

**Comment by tijmenb** [comment]
Closing.

This is actually sending `tags` to panopticon, which won't save them. This PR should be part of a bigger story, which also updates panopticon: https://trello.com/c/IgYwT6yM. Will be reopened when we attack that story.

**Comment by tijmenb** [comment]
Turns out that panopticon automatically saves the content_id:

```shell
12:34:38 panopticon.1              | 
12:34:38 panopticon.1              | Started PUT "/tags/specialist_sector/running-charity/managing-charity.json" for 127.0.0.1 at 2015-09-17 12:34:38 +0000
12:34:38 panopticon.1              | Processing by TagsController#update as JSON
12:34:38 panopticon.1              |   Parameters: {"content_id"=>"cf2ab891-5bd9-4788-8254-f9444423719c", "description"=>"List of information about Managing your charity.", "parent_id"=>"running-charity", "tag_id"=>"running-charity/managing-charity", "tag_type"=>"specialist_sector", "title"=>"Managing your charity", "id"=>"specialist_sector/running-charity/managing-charity", "tag"=>{"content_id"=>"cf2ab891-5bd9-4788-8254-f9444423719c", "description"=>"List of information about Managing your charity.", "parent_id"=>"running-charity", "tag_id"=>"running-charity/managing-charity", "tag_type"=>"specialist_sector", "title"=>"Managing your charity"}}
12:34:38 panopticon.1              | MONGODB (0ms) govuk_content_development['tags'].find({:_id=>"specialist_sector/running-charity/managing-charity"}).limit(-1).sort([[:_id, :asc]])
12:34:38 panopticon.1              | MONGODB (0ms) govuk_content_development['tags'].find({:tag_type=>"specialist_sector", :tag_id=>{"$in"=>["running-charity/managing-charity"]}})
12:34:38 panopticon.1              | MONGODB (0ms) govuk_content_development['tags'].update({"_id"=>BSON::ObjectId('5342965b40f0b67aae000010')}, {"$set"=>{"content_id"=>"cf2ab891-5bd9-4788-8254-f9444423719c", "description"=>"List of information about Managing your charity."}})
12:34:38 panopticon.1              | Completed 200 OK in 3.3ms
12:34:38 panopticon.1              | 
```

This PR is enough to get https://trello.com/c/IgYwT6yM done.

**Comment by tijmenb** [comment]
Added a rake task that should be run after deploy.

**Comment by alext** [comment]
> Turns out that panopticon automatically saves the content_id:

I think that's slightly accidental because of how Mongoid works with extra attributes. The Tag model itself doesn't have a content_id field - https://github.com/alphagov/govuk_content_models/blob/master/app/models/tag.rb#L8-L14. I think it would be better to update the model to make this explicit.

**Comment by tijmenb** [comment]
Allright, I'll update Panopticon. Closing this until then.

**Comment by tijmenb** [comment]
Reopening this, as https://github.com/alphagov/panopticon/pull/299 will update panopticon to have a Tag#content_id field. This can  probably be safely merged in the meantime, specifying the field in Mongoid is not strictly necessary afaik (saving the `content_id` already works without those PRs).

**Pull request merged**
