### PR TITLE
Add a Rake task to toggle the livestream

### PR DESCRIPTION
**Pull request by edwardkerry**
- We have an "extended hours" rota from 1430 to 2200 every weekday whose
  "extra" job consists of editing three lines of YAML, clicking a button
  in Collections Publisher, then reverting the three lines of YAML and
  clicking the same button, to enable and disable the coronavirus press
  conference live stream. It requires two people: one to raise the PR,
  and one to approve the PR, in each case.
- In an effort to save ourselves some work, here's a Rake task that we
  can run through Jenkins (maybe Content Designers can run it - some of
  them can already run some tasks?).
- This publishes the draft content item. We still have to use the UI
  buttons in Collections Publisher to make the draft LIVE.
- Run with
  `'publishing_api:coronavirus_livestream[true, 32nd April 2020]'`
  to enable for a date (it doesn't check that the date is valid), and
  `'publishing_api:coronavirus_livestream[false]'` to disable.

Co-authored-by: Ed Kerry <edward.kerry@digital.cabinet-office.gov.uk>
Co-authored-by: Issy Long <issy.long@digital.cabinet-office.gov.uk>

### CODE REVIEW

**Comment by sihugh** [comment]
This is great, thanks.  We'll add a card to bring this into the publishing app so that content people can do the updates.  One risk is that people may change the status of the live stream by publishing unrelated content changes, so we'll have to think about how that works

**Comment by issyl0** [comment]
@sihugh I'm confused. So this isn't mergeable? Or it is, but in a different app? Which publishing app are you talking about, because this is Collections Publisher right here. It's also a little weird that the content is in a separate repo...

**Comment by sihugh** [comment]
> @sihugh I'm confused. So this isn't mergeable? Or it is, but in a different app? Which publishing app are you talking about, because this is Collections Publisher right here. It's also a little weird that the content is in a separate repo...

It's not exactly a mature publishing experience.  We deliberately put the content somewhere else so we don;t accrue a deploy backlog that makes zero difference to the app.  I think that'd be more confusing.  

With this approach, we're at risk of overwriting the livestream config if someone publishes content via the standard route. I think the answer is to persist the livestream config in the app db and remove it entirely from the yaml.  I'll do something in that vein.

**Comment by issyl0** [comment]
Looks like this is superseded by #996.

**Pull request closed without merging**
